// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	submission "github.com/alanwade2001/spa-submissions-api/models/generated/submission"
	mock "github.com/stretchr/testify/mock"
)

// CustomerAPI is an autogenerated mock type for the CustomerAPI type
type CustomerAPI struct {
	mock.Mock
}

// Find provides a mock function with given fields: user
func (_m *CustomerAPI) Find(user submission.UserReference) (*submission.CustomerReference, error) {
	ret := _m.Called(user)

	var r0 *submission.CustomerReference
	if rf, ok := ret.Get(0).(func(submission.UserReference) *submission.CustomerReference); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*submission.CustomerReference)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(submission.UserReference) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
