// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	initiation "github.com/alanwade2001/spa-submissions-api/models/generated/initiation"
	mock "github.com/stretchr/testify/mock"
)

// MessageAPI is an autogenerated mock type for the MessageAPI type
type MessageAPI struct {
	mock.Mock
}

// SendInitiation provides a mock function with given fields: i
func (_m *MessageAPI) SendInitiation(i initiation.InitiationModel) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(initiation.InitiationModel) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
